version: "3.8"  # optional but recommended for compatibility

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: swasthi_backend_be
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app  # for hot reload
    environment:
      - PYTHONPATH=/app  # ensures FastAPI finds modules inside /src
    command: ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
